### ISSUE TITLE
Help installing

### ISSUE THREAD

**Issue by Cypher1983** [bitshiftza/fnb-api#1]
Firstly, thank you for the script.

But, could you please provide instructions to get it to work in a laravel project?

Looking forward to your reply.

**Comment by SydneyCodeWorkz** [comment]
not sure is this will help, its been almost a year since the question. 
First go to root folder and run "npm install", this will install all the webpack stuff your laravel app needs.
then afterwards u run "npm i fnb-api "
now there is a filer under yourAppFolder\resources\assets\js called App.js make sure thats included your main laravel header page or at the bottom of your <body></body> tags along side your other js scripts.

now open the App.js script where you will now perfom the instructions illustrated in the readme of the npm page on how to include the the package.  

create a new js file which you will write out your functions which your laravel php page will execute on-click or on-load depends. make sure to include it below the App.js in the main app page. So to access these functions you would simply call on-click event on the button or link in laravel php page to execute the js function related to the desired instruction.
